#test#
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stage
      - uat
      - develop
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  call-template:
    uses: naresh4b9/cicd-templates/.github/workflows/ci-cd-template.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || github.ref_name == 'uat' && 'uat' || 'dev' }}
      docker-image-tag: aiapp-${{ github.ref_name }}-${{ github.sha }}
    secrets: inherit
